# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

name: static-site
description: 
author:
  name: Test
  email: rob@voom-interactive.com

# Grunt handles images and assets.
exclude: ['images', 'scripts', 'styles', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

include: []

languages: ["en", "hu"]

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true

markdown: redcarpet
pygments: true
